### ISSUE TITLE
Clean up your README.md

### ISSUE THREAD

**Issue by TehSeph** [Kusoneko/Nekobot#7]

**Comment by Lirusaito** [comment]
How's that?

**Comment by TehSeph** [comment]
**Much** better than before. Might also be worth splitting up the different options in Configure.md into similarly grouped categories as well. The long format makes it hard to find what you're looking for just at a glance and also feels unorganized.

**Comment by TehSeph** [comment]
LOL sorry **just** closed this and already found something off.
Quick links still a bit hard to read. Try something spacing them out like:

Quick links to descriptions: [Credentials](#credentials) | [master](#master) | [server](#server) | [prefix, prefixprivate, prefix and mentioncommand](#prefix) | [helpmode](#helpmode) | [loglevel](#log-level) | [game](#game) | [musicFolder, and musicUseSubfolders](#music-folder) | [pitur, gold, cosplay](#image-folders)

**Comment by TehSeph** [comment]
:+1:
