### ISSUE TITLE
Potentially switch NAudio for FFMPEG

### ISSUE THREAD

**Issue by Kusoneko** [Kusoneko/Nekobot#8]
Since the voice problems of randomly going mute are due to exceptions thrown by NAudio. For some reason, no matter the fix we try to implement, it still doesn't really fix it completely. (We tried !reset & !forcereset and that other fix which retries a couple of time when getting that exception before moving on.) Neither actually fix it once that exception happens. Also, using FFMPEG means support for every file extension ever, so no more issues with downloading codecs for streaming from places that use specific formats.

**Comment by Lirusaito** [comment]
Are we sure it's going mute from NAudio exceptions?

**Comment by Kusoneko** [comment]
More or less, the chat goes mute after the exceptiom thrown by NAudio, however, the reset fix shows that it might be muted by Discord.net somehow, because when used after the chat goes mute, the bot is able to disconnect from the voice server, however, reconnecting leads to a "The client is connecting..." error, with absolutely no other details. Basically, the NAudio exception is pretty much the trigger but the muting might come from just about anywhere, so does Nekobot suddenly leaving a server after a while following that exception. Although waiting for Discord.Net 0.9 before doing anything like switching libs might be a good idea, maybe the rewritten stuff for multi-server will have fixed it somehow.

**Comment by Kusoneko** [comment]
Hmmm... We don't really need this issue much anymore considering the reason we considered that has been more or less fixed a while back. Guess I'll close it.
